### PR TITLE
a few fixes to get towards compiling

### PR DESCRIPTION
**Pull request by GeorgeLuo**

### CODE REVIEW

**Comment by GeorgeLuo** [comment]
@googlebot I consent.

**Comment by nhant01** [comment]
> All (the pull request submitter and all commit authors) CLAs are signed, **but** one or more commits were authored or co-authored by someone other than the pull request submitter.
> 
> We need to confirm that all authors are ok with their commits being contributed to this project. Please have them confirm that by leaving a comment that contains only `@googlebot I consent.` in this pull request.
> 
> _Note to project maintainer:_ There may be cases where the author cannot leave a comment, or the comment is not properly detected as consent. In those cases, you can manually confirm consent of the commit author(s), and set the `cla` label to `yes` (if enabled on your project).
> 
> ℹ️ **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fampproject%2Fvalidator-java%2Fpull%2F4) for more info**.

**Comment by nhant01** [comment]
@googlebot I consent.

**Comment by GeorgeLuo** [comment]
@Gregable can you unblock? Not idea who who googlebot is looking for

**Comment by Gregable** [comment]
@rsimha Do you have a good idea what Googlebot wants here?

@GeorgeLuo - I don't know how to make the bot happy, but I can forge merge. Would you like me to do that?

**Comment by rsimha** [comment]
> @rsimha Do you have a good idea what Googlebot wants here?

Seems like the bot is complaining that some of @nhant01's commits are included in the PR, but they haven't explicitly consented.

> @GeorgeLuo - I don't know how to make the bot happy, but I can forge merge. Would you like me to do that?

There are two ways to satisfy the check and avoid having to force merge: 
1. @nhant01 replies with `@googlebot I consent`.
2. A Googler (@Gregable or me) manually sets the `cla: yes` label on the PR, thereby satisfying the check.

Let's try 1 and then 2, and if neither works, we can force merge.

**Comment by nhant01** [comment]
@googlebot I consent.

**Comment by Gregable** [comment]
Ah, good catch. I thought @nhant01 had already done one of these. I guess maybe not. Either way, it looks to be working now!

**Pull request merged**
