### PR TITLE
Switch from Travis to GitHub Actions

### PR DESCRIPTION
**Pull request by danielrozenberg**
TODO:

- [ ] Verify that anyone can trigger the test.yml workflow with a PR
- [x] Set up secret environment variables for Maven/GPG passwords, add it to the publish-mavel-package.yml file
- [ ] Verify that only push builds to `master` trigger the publish-maven-package.yml workflow
- [ ] Verify that the auto-generated settings.xml file is usable (see the "`settings.xml` file created for the second deploy to Apache Maven Central" code example " under the [yaml example](https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#yaml-example) header)

### CODE REVIEW

**Comment by danielrozenberg** [comment]
Seems that I cannot assign PRs to people, so here are some tags: @nhant01 @Gregable @rsimha

**Review by nhant01 — COMMENTED** [review]
@danielrozenberg can you also delete .travis.yml file? This file is no longer required.

**Review by rsimha — APPROVED** [review]
LGTM modulo any changes requested by @nhant01 and @Gregable. I'll let Greg merge once the environment variables are set up.

**Comment by nhant01** [comment]
> LGTM modulo any changes requested by @nhant01 and @Gregable. I'll let Greg merge once the environment variables are set up.

@Gregable I assumed you need the Sonatype credentials (both OSSRH and GPG values) we created. Let me know, I can send you in private email or slack.

**Comment by nhant01** [comment]
@danielrozenberg what should the build status be on the README?

Currently, we have 
Build status: [build_status](https://travis-ci.com/ampproject/validator-java)

**Comment by danielrozenberg** [comment]
Good catch! Unfortunately until we merge this PR the badge URL returns 404 - I can create a followup PR to submit immediately after this one

**Comment by nhant01** [comment]
@danielrozenberg Are the TODOs done? Are we able to merge yet?

**Comment by danielrozenberg** [comment]
Turns out we can't test that the workflows work until after merging the PR, so we did just that. Will follow up with any necessary fixes

**Pull request merged**
